package com.demo.spdemo.controller;


import com.demo.spdemo.dao.UserInfoMapper;
import com.demo.spdemo.entity.UserInfo;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.stereotype.Service;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.servlet.ModelAndView;

import javax.annotation.Resource;

@Service("userInfoService")
@ComponentScan("com.demo.spdemo.dao")
public class UserInfoService implements UserInfoMapper {

    @Resource
    public UserInfoMapper userInfoMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    public ModelAndView deleteByPrimaryKey(@PathVariable("id") Integer id,Model model)
    {
        userInfoMapper.deleteByPrimaryKey(id);
        return new ModelAndView("/user/deleteok","userModel" ,model);
    }

    @Override
    public int deleteByPrimaryKey(Integer userId) {
        return 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    @Override
    public int insert(UserInfo record) {
        return userInfoMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    @Override
    public int insertSelective(UserInfo record) {
        return 0;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    @Override
    public UserInfo selectByPrimaryKey(Integer id) {
        return userInfoMapper.selectByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    @Override
    public int updateByPrimaryKeySelective(UserInfo record) {
        return 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    @Override
    public int updateByPrimaryKey(UserInfo record) {
        return 0;
    }
}
